@startuml{plantuml_class_sample.svg}
title <size:18> クラス図 のサンプル </size>
skinparam {
  defaultFontName "Migu 1M"
}
package Geometry {
class Canvas
abstract Figure {
    #{static} const size_t ParseBufferSize = 256
    +{abstract} size_t getPointsNum()
    +{static} Figure *ParseString(const char *str)
}

Figure "0..*" o- "1" Canvas : 集約

Polygon <|-- Rect : 汎化
Figure <|-- Polygon : 汎化
Figure <|-- Ellipse : 汎化
Ellipse <|-- Circle : 汎化
}

@enduml